### ISSUE TITLE
Podcast/Play - Establish Wordpress API Connection

### ISSUE THREAD

**Issue by tedyw** [osqledaren/osqledaren-angular2#4]
Establish connection to retrieve meta-data from Wordpress. (Hint: Look how the current implementation for articles work.)

**Comment by AZNanoi** [comment]
The API connection between Podcast and Wordpress is already done. Connection between Play and Wordpress is needed to establish.

**Comment by tedyw** [comment]
Bumped WP-API to official core version in 4.7. Unsure if the plugin version will be further maintained. ?filter[...] query parameter doesn't exist anymore. HTTP requests needs to be updated.

Official documentation for core WP-API can be found here.
https://developer.wordpress.org/rest-api/

Podcast and play post types may need to be added as a rest endpoint
https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-rest-api-support-for-custom-content-types/

**Comment by AZNanoi** [comment]
Established Wordpress API Connection with Play service d9dbc245f6f450f89023e2a2679388bb14f97f3b

**Comment by AZNanoi** [comment]
Established Wordpress API Connection with Podcast service 37688ea0a406639fe5636fd1d3b87d8366995f86
