### ISSUE TITLE
Play: Store queue's data in Cookies storage?

### ISSUE THREAD

**Issue by AZNanoi** [osqledaren/osqledaren-angular2#96]
The data in the play-queue is lost on page reload. Should we store queue's data in Cookies or local storage?

**Comment by tedyw** [comment]
Just updated the master branch to include angular2-cookie for OAuth2 authenticated requests to Wordpress. You should check it out. What data type are you using to store the queue?

**Comment by AZNanoi** [comment]
Great! I am gonna store IDs of podcasts in cookies for the queue.

**Comment by AZNanoi** [comment]
Added cookies service for Play's queue. Slugs of podcasts are stored in the cookies instead, because podcasts are not retrievable by ID number. cbab1f0ec5738f8e101e79f88ef74dccdfcbbbbc
